version: "3.9"

services:
  db:
    image: postgres:18-alpine
    container_name: db
    restart: unless-stopped
    environment:
      POSTGRES_USER: geny_stunt
      POSTGRES_PASSWORD: securepassword123
      POSTGRES_DB: geny_stunt_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - endence

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    restart: unless-stopped
    # Injeksi DATABASE_URL langsung sebelum command prisma
    command: >
      sh -c "DATABASE_URL=postgresql://geny_stunt:securepassword123@db:5432/geny_stunt_db?schema=public npx prisma db push && 
             DATABASE_URL=postgresql://geny_stunt:securepassword123@db:5432/geny_stunt_db?schema=public npx prisma db seed && 
             npm run start:dev"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://geny_stunt:securepassword123@db:5432/geny_stunt_db?schema=public"
    ports:
      - "3000:3000"
    networks:
      - endence

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    restart: unless-stopped
    # Pakai npm run dev sesuai script di package.json lo
    command: npm run dev
    depends_on:
      - backend
    ports:
      - "4000:3000"
    networks:
      - endence

volumes:
  postgres_data:
networks:
  endence:
    driver: bridge
