version: "3.9"

services:
  db:
    image: postgres:18-alpine
    # container_name dihapus agar Coolify bisa manage scaling kalau butuh
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - endence

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    restart: unless-stopped
    # Di Production, kita pakai 'migrate deploy' agar aman.
    # Tapi kalau lo mau otomatis kayak di lokal, pakai ini:
    command: sh -c "npx prisma db push && npx prisma db seed && npm run start:prod"
    depends_on:
      - db
    environment:
      DATABASE_URL: ${DATABASE_URL}
    networks:
      - endence
    # Port mapping biasanya diatur di UI Coolify, tapi biarin buat internal

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    restart: unless-stopped
    # DI PRODUCTION HARUS BUILD DULU
    command: sh -c "npm run build && npm run start"
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    networks:
      - endence

volumes:
  postgres_data:
networks:
  endence:
    driver: bridge
