version: "3.9"

x-service-base: &service-base
  init: true
  restart: unless-stopped
  environment:
    TZ: "Europe/Paris"

x-volume-base: &volume-base
  driver: local

services:
  db:
    <<: *service-base
    image: postgres:18
    container_name: db
    env_file:
      - backend/.env
    networks:
      - endence
    volumes:
      - db-data:/var/lib/postgresql

  backend:
    <<: *service-base
    depends_on:
      - db
    container_name: backend
    command: npm run start:dev
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    env_file:
      - backend/.env
    volumes:
      - ./backend:/usr/src/app
      # - /usr/src/app/node_modules
    ports:
      - "3000:3000" # backend API
    networks:
      - endence

  frontend:
    <<: *service-base
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "4000:3000" # frontend Next.js
    depends_on:
      - backend
    networks:
      - endence
    environment:
  - NEXT_PUBLIC_API_URL=http://localhost:4000
  - API_INTERNAL_URL=http://backend:4000


  studio:
    <<: *service-base
    container_name: prisma_studio
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    depends_on:
      - backend
    command: npx prisma studio --port 5555
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "5556:5555"
    networks:
      - endence
    env_file:
      - ./backend/.env


networks:
  endence:
    driver: bridge

volumes:
  db-data:
    <<: *volume-base
