version: "3.9"

services:
  db:
    image: postgres:18-alpine
    container_name: db
    restart: unless-stopped
    # Masukin env dasar di sini biar DB nggak mogok pas startup
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: stuntcare
      POSTGRES_PASSWORD: password_lo_disini # GANTI INI
    networks:
      - endence
    volumes:
      - db-data:/var/lib/postgresql/data

  backend:
    container_name: backend
    restart: unless-stopped
    # sh -c digunakan agar bisa menjalankan generate prisma sebelum aplikasi start
    command: sh -c "npx prisma generate && npm run start:dev"
    build:
      context: .
      dockerfile: backend/Dockerfile.backend
    depends_on:
      - db
    ports:
      - "3000:3000"
    networks:
      - endence
    # Untuk server, isi DATABASE_URL di dashboard Coolify saja

  frontend:
    container_name: frontend
    restart: unless-stopped
    build:
      context: .
      dockerfile: frontend/Dockerfile.frontend
    ports:
      - "4000:3000"
    depends_on:
      - backend
    networks:
      - endence
    environment:
      TZ: "Europe/Paris"
      NEXT_PUBLIC_API_URL: "https://api.genystuntcare.cloud"
      API_INTERNAL_URL: "http://backend:3000"

  studio:
    container_name: prisma_studio
    restart: unless-stopped
    # Pakai image yang sama dengan backend tapi jalankan prisma studio
    build:
      context: .
      dockerfile: backend/Dockerfile.backend
    command: npx prisma studio --port 5555
    depends_on:
      - backend
    ports:
      - "5556:5555"
    networks:
      - endence

networks:
  endence:
    driver: bridge

volumes:
  db-data:
    driver: local
