version: "3.9"

x-service-base: &service-base
  init: true
  restart: unless-stopped
  environment:
    TZ: "Europe/Paris"

x-volume-base: &volume-base
  driver: local

version: "3.9"

services:
  db:
    image: postgres:18-alpine
    container_name: db
    restart: unless-stopped
    environment:
      POSTGRES_USER: geny_stunt
      POSTGRES_PASSWORD: securepassword123
      POSTGRES_DB: geny_stunt_db
    networks:
      - endence
    volumes:
      - db-data:/var/lib/postgresql/data

  backend:
    container_name: backend
    restart: unless-stopped
    # Generate prisma dulu baru jalanin nest
    command: sh -c "npx prisma generate && npm run start:dev"
    build:
      context: .
      dockerfile: backend/Dockerfile.backend
    depends_on:
      - db
    environment:
      # Langsung tulis string aslinya biar Docker nggak bingung render variabel
      DATABASE_URL: "postgresql://geny_stunt:securepassword123@db:5432/geny_stunt_db?schema=public"
    ports:
      - "3000:3000"
    networks:
      - endence

  frontend:
    container_name: frontend
    restart: unless-stopped
    build:
      context: .
      dockerfile: frontend/Dockerfile.frontend
    ports:
      - "4000:3000"
    depends_on:
      - backend
    networks:
      - endence
    environment:
      TZ: "Europe/Paris"
      NEXT_PUBLIC_API_URL: "https://api.genystuntcare.cloud"
      API_INTERNAL_URL: "http://backend:3000"

  studio:
    container_name: prisma_studio
    restart: unless-stopped
    build:
      context: .
      dockerfile: backend/Dockerfile.backend
    command: npx prisma studio --port 5555
    depends_on:
      - backend
    environment:
      DATABASE_URL: "postgresql://geny_stunt:securepassword123@db:5432/geny_stunt_db?schema=public"
    ports:
      - "5556:5555"
    networks:
      - endence

networks:
  endence:
    driver: bridge

volumes:
  db-data:
    driver: local